# Generated by Django 2.2.13 on 2021-01-17 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Douban', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='T2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_star', models.IntegerField()),
                ('short', models.CharField(max_length=400)),
                ('sentiment', models.FloatField()),
            ],
            options={
                'db_table': 't2',
                'managed': True,
            },
        ),
        migrations.DeleteModel(
            name='T1',
        ),
    ]
