# Generated by Django 2.2.13 on 2021-01-18 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.CharField(max_length=400, null=True)),
                ('star_review', models.FloatField(null=True)),
                ('comments_time', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'comments',
                'managed': True,
            },
        ),
    ]
